services:
  - type: web
    name: mercadito
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
